name: wikitest
on:
  push:
    branches:
      - main

jobs:
  sync_to_oss:
    runs-on: ubuntu-latest
    steps:
      - run: curl https://rclone.org/install.sh | sudo bash
      - env:
          OSS_KEY: ${{ secrets.OSS_KEY }}
          OSS_SECRET: ${{ secrets.OSS_SECRET }}
        run: |
          rclone config create oss s3 provider Alibaba access_key_id $OSS_KEY secret_access_key $OSS_SECRET endpoint oss-cn-shenzhen.aliyuncs.com acl public-read
      - run: curl -OL https://github.com/aliyun/aliyun-cli/releases/download/v3.0.243/aliyun-cli-linux-3.0.243-amd64.tgz
      - run: tar xzvf aliyun-cli-linux-3.0.243-amd64.tgz && chmod u+x ./aliyun && mv ./aliyun /usr/local/bin/aliyun
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm install yarn
      - run: yarn config set registry https://registry.yarnpkg.com
      - run: yarn config get registry
      - run: yarn config set strict-ssl false
      - run: yarn install
      - run: yarn run build
      - run: rclone -v --exclude='.git**' --exclude='.idea**' copy docs/.vuepress/dist/ oss:risinghf-wiki
      - run: aliyun configure set --access-key-id ${{ secrets.ALICLOUD_ACCESS_KEY }}  --access-key-secret ${{ secrets.ALICLOUD_SECRET_KEY }} --profile default --mode AK --region shenzhen
      - run: aliyun cdn RefreshObjectCaches --ObjectType Directory --ObjectPath https://wiki.risinghf.com/