name: wikitest
on:
  push:
    branches:
      - main

jobs:
  sync_to_oss:
    runs-on: ubuntu-latest
    steps:
      - run: curl https://rclone.org/install.sh | sudo bash
      - env:
          OSS_KEY: ${{ secrets.OSS_KEY }}
          OSS_SECRET: ${{ secrets.OSS_SECRET }}
        run: |
          rclone config create oss s3 provider Alibaba access_key_id $OSS_KEY secret_access_key $OSS_SECRET endpoint oss-cn-shenzhen.aliyuncs.com acl public-read
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm install yarn
      - run: yarn config get registry
      - run: yarn config set registry https://registry.yarnpkg.com
      - run: yarn config get registry
      - run: yarn install
      - run: yarn run build
      - run: rclone -v --exclude='.git**' --exclude='.idea**' copy docs/.vuepress/dist/ oss:risinghf-wiki
      - run: curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" && unzip awscliv2.zip && sudo ./aws/install --update
      - env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"
